services:
  fcp-data-access-layer-api:
    image: node:18
    container_name: fcp-data-access-layer-api-dev
    ports:
      - ${PORT}:${PORT}
      - ${PORT_MOCK}:${PORT_MOCK}
    command: npm run start:dev
    volumes:
      - ./:/usr/local/dev/fcp-data-access-layer-api
    working_dir: /usr/local/dev/fcp-data-access-layer-api
    env_file:
      - .env
