name: fcp-data-access-layer-api
namespace: ffc-dal
image: fcp-data-access-layer-api

labels: {}

deployment:
  priorityClassName: low
  minReadySeconds: 5

service:
  port: 80
  type: ClusterIP
  
container:
  port: 3000
  memCpuTier: M

ingress:
  class: nginx
  endpoint: ffc-dal
  server: example.com

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 60
  periodSeconds: 10
  failureThreshold: 3

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 70
  periodSeconds: 10
  failureThreshold: 3

aadWorkloadIdentity: true

serviceAccount:
  name: ffc-dal
  roleArn: true