"""
Represents the status of a business application.
"""
type BusinessApplicationStatus {
  """
  The open status of the business application.
  """
  open: String

  """
  The status of the business application.
  """
  status: String

  """
  The type of the business application.
  """
  type: String

  """
  The sector of the business application.
  """
  sector: String

  """
  The year of the business application.
  """
  year: Int

  """
  The FRN (Farm Reference Number) of the business application.
  """
  frn: String

  """
  The office of the business application.
  """
  office: String
}

"""
Represents a claim of a business application.
"""
type BusinessApplicationClaim {
  """
  The schema year of the business application claim.
  """
  schemaYear: Int

  """
  The type of the business application claim.
  """
  type: String

  """
  The status of the business application claim.
  """
  status: String

  """
  The last movement of the business application claim.
  """
  lastMovement: String
}

"""
Represents the payment details of a business.
"""
type BusinessApplicationPayment {
  """
  The Firm Reference number of the payment.
  """
  firmReferenceNumber: String

  """
  The BACS reference of the payment.
  """
  bacsRef: String

  """
  The payment date of the payment.
  """
  paymentDate: String

  """
  The agreement claim number of the payment.
  """
  agreementClaimNumber: String

  """
  The scheme of the payment.
  """
  scheme: String

  """
  The marketing year of the payment.
  """
  marketingYear: String

  """
  The description of the payment.
  """
  description: String

  """
  The transaction amount of the payment.
  """
  transactionAmount: String

  """
  The transaction currency of the payment.
  """
  transactionCurrency: String
}

"""
Represents a business application.

Data Source: Rural Payments Portal (PRR)
"""
type BusinessApplication {
  """
  The agreement claim number of the payment.
  """
  applicationId: ID

  """
  The status of the business application.
  """
  applicationStatus: BusinessApplicationStatus

  """
  The claim of the business application.
  """
  csClaim: BusinessApplicationClaim

  """
  The payments of the business application.
  """
  payments: [BusinessApplicationPayment]
}
