"""
Represents a coordinate with x and y values.
"""
type CPHCoordinate {
  """
  The x value of the coordinate.
  """
  x: Int @on

  """
  The y value of the coordinate.
  """
  y: Int @on
}

"""
Represents a County Parish Holding (CPH) number.

Data Source: Rural Payments Portal (PRR)
"""
type CPH {
  """
  The CPH number.
  """
  number: String @on

  """
  The parcel numbers associated with the CPH number.
  """
  parcelNumbers: [String] @on

  """
  The parish associated with the CPH number.
  """
  parish: String @on

  """
  The start date of the CPH number.
  """
  startDate: Int @on

  """
  The expiry date of the CPH number.
  """
  expiryDate: Int @on

  """
  The species associated with the CPH number.
  """
  species: [String] @on

  """
  The coordinate of the CPH number.
  """
  coordinate: CPHCoordinate @on
}
