"""
Represents the name of a business land cover.
"""
enum BusinessLandCoverName {
  """
  Represents permanent grassland.
  """
  PERMANENT_GRASSLAND

  """
  Represents permanent crops.
  """
  PERMANENT_CROPS

  """
  Represents arable land.
  """
  ARABLE_LAND
}

"""
Represents a parcel of a business land.
"""
type BusinessLandParcel {
  """
  The unique identifier of the land parcel.
  """
  id: ID!

  """
  The sheet ID of the land parcel.
  """
  sheetId: String

  """
  The parcel ID of the land parcel.
  """
  parcelId: String

  """
  The area of the land parcel.
  """
  area: Float

  """
  Whether the parcel is pending digitisation.
  """
  pendingDigitisation: Boolean
}

"""
Represents a summary of a business land.
"""
type BusinessLandSummary {
  """
  The area of arable land.
  """
  arableLandArea: Float

  """
  The area of permanent crops.
  """
  permanentCropsArea: Float

  """
  The area of permanent grassland.
  """
  permanentGrasslandArea: Float

  """
  The total area of the business land.
  """
  totalArea: Float

  """
  The total number of parcels in the business land.
  """
  totalParcels: Float
}

"""
Represents a cover of a business land.
"""
type BusinessLandCover {
  """
  The unique identifier of the land cover.
  """
  id: ID!

  """
  The name of the land cover.
  """
  name: BusinessLandCoverName

  """
  The area of the land cover.
  """
  area: Float

  """
  The code of the land cover.
  """
  code: String
}

"""
Represents a business land.

Data Source: Rural Payments Portal (PRR)
"""
type BusinessLand {
  """
  The parcels of the business land.
  """
  parcels(date: Date): [BusinessLandParcel] @on

  """
  A single parcel of the business land.
  """
  parcel(date: Date, parcelId: ID!): BusinessLandParcel @on

  """
  The covers of a single parcel of the business land.
  """
  parcelCovers(date: Date, parcelId: ID!): [BusinessLandCover]

  """
  The summary of the business land.
  """
  summary(historicDate: Date): BusinessLandSummary
}
