- key: Sentinel
  value: '2'
- key: ENABLE_MOCK_SERVER
  value: 'true'
- key: RURAL_PAYMENTS_AGENCY_LAND_API_URL
  value: 'https://environment.data.gov.uk'
- key: RURAL_PAYMENTS_PORTAL_EMAIL
  value: 'example@email.com'
- key: RURAL_PAYMENTS_PORTAL_API_URL
  value: 'http://127.0.0.1:3100/rpp/'
- key: RURAL_PAYMENTS_PROXY_URL
  value: ''
- key: ENTRA_ID_TTL_IN_SECONDS
  value: '60'
- key: ENTRA_ID_URL
  value: 'https://graph.microsoft.com'
# Secrets
- key: RURAL_PAYMENTS_PORTAL_PASSWORD
  value: '{{servicename}}-RURAL-PAYMENTS-PORTAL-PASSWORD'
  type: 'keyvault'
- key: API_TENANT_ID
  value: '{{servicename}}-API-TENANT-ID'
  type: 'keyvault'
- key: ADMIN_AD_GROUP_ID
  value: '{{servicename}}-ADMIN-AD-GROUP-ID'
  type: 'keyvault'
- key: AUTHENTICATE_DB_HOST
  value: '{{servicename}}-AUTHENTICATE-DB-HOST'
  type: 'keyvault'
- key: AUTHENTICATE_DB_SCHEMA
  value: '{{servicename}}-AUTHENTICATE-DB-SCHEMA'
  type: 'keyvault'
- key: AUTHENTICATE_DB_USERNAME
  value: '{{servicename}}-AUTHENTICATE-DB-USERNAME'
  type: 'keyvault'
- key: AUTHENTICATE_DB_PASSWORD
  value: '{{servicename}}-AUTHENTICATE-DB-PASSWORD'
  type: 'keyvault'
- key: AUTHENTICATE_DB_USERNAME_AUDIT_WRITE
  value: '{{servicename}}-AUTHENTICATE-DB-USERNAME-AUDIT-WRITE'
  type: 'keyvault'
- key: AUTHENTICATE_DB_PASSWORD_AUDIT_WRITE
  value: '{{servicename}}-AUTHENTICATE-DB-PASSWORD-AUDIT-WRITE'
  type: 'keyvault'
