- key: Sentinel
  value: '2'
- key: RURAL_PAYMENTS_PORTAL_API_URL
  value: 'http://127.0.0.1:3100/rpp/'
- key: LOG_LEVEL
  value: 'debug'
- key: VERSION_1_PAGE_SIZE
  value: '10000'
- key: ENVIRONMENT
  value: 'snd3'
- key: HEALTH_CHECK_ENABLED
  value: 'true'

# Secrets
- key: API_TENANT_ID
  value: '{{servicename}}-API-TENANT-ID'
  type: 'keyvault'
- key: ADMIN_AD_GROUP_ID
  value: '{{servicename}}-ADMIN-AD-GROUP-ID'
  type: 'keyvault'
- key: AUTHENTICATE_DB_HOST
  value: '{{servicename}}-AUTHENTICATE-DB-HOST'
  type: 'keyvault'
- key: AUTHENTICATE_DB_SCHEMA
  value: '{{servicename}}-AUTHENTICATE-DB-SCHEMA'
  type: 'keyvault'
- key: AUTHENTICATE_DB_USERNAME
  value: '{{servicename}}-AUTHENTICATE-DB-USERNAME'
  type: 'keyvault'
- key: AUTHENTICATE_DB_PASSWORD
  value: '{{servicename}}-AUTHENTICATE-DB-PASSWORD'
  type: 'keyvault'
- key: RP_INTERNAL_APIM_TENANT_ID
  value: '{{servicename}}-RP-INTERNAL-APIM-TENANT-ID'
  type: 'keyvault'
- key: RP_INTERNAL_APIM_CLIENT_ID
  value: '{{servicename}}-RP-INTERNAL-APIM-CLIENT-ID'
  type: 'keyvault'
- key: RP_INTERNAL_APIM_CLIENT_SECRET
  value: '{{servicename}}-RP-INTERNAL-APIM-CLIENT-SECRET'
  type: 'keyvault'
- key: RP_INTERNAL_APIM_SUBSCRIPTION_KEY
  value: '{{servicename}}-RP-INTERNAL-APIM-SUBSCRIPTION-KEY'
  type: 'keyvault'
- key: RP_INTERNAL_APIM_SCOPE
  value: '{{servicename}}-RP-INTERNAL-APIM-SCOPE'
  type: 'keyvault'
- key: RP_INTERNAL_APIM_ACCESS_TOKEN_URL
  value: '{{servicename}}-RP-INTERNAL-APIM-ACCESS-TOKEN-URL'
  type: 'keyvault'
- key: RP_INTERNAL_APIM_URL
  value: '{{servicename}}-RP-INTERNAL-APIM-URL'
  type: 'keyvault'
- key: RURAL_PAYMENTS_PORTAL_EMAIL
  value: '{{servicename}}-RURAL-PAYMENTS-PORTAL-EMAIL'
  type: 'keyvault'
- key: AUTHENTICATE_DB_USERNAME_AUDIT_WRITE
  value: '{{servicename}}-AUTHENTICATE-DB-USERNAME-AUDIT-WRITE'
  type: 'keyvault'
- key: AUTHENTICATE_DB_PASSWORD_AUDIT_WRITE
  value: '{{servicename}}-AUTHENTICATE-DB-PASSWORD-AUDIT-WRITE'
  type: 'keyvault'
- key: HEALTH_CHECK_RP_INTERNAL_ORGANISATION_ID
  value: '{{servicename}}-HEALTH-CHECK-RP-INTERNAL-ORGANISATION-ID'
  type: 'keyvault'
- key: EVENT_HUB_NAME
  value: '{{servicename}}-EVENT-HUB-NAME'
  type: 'keyvault'
- key: EVENT_HUB_CONNECTION_STRING
  value: '{{servicename}}-EVENT-HUB-CONNECTION-STRING'
  type: 'keyvault'
